import { Tooltip } from "antd";
import type { CSSProperties, ReactNode } from "react";
import { useEffect, useRef, useState } from "react";

import { quotas } from "./quota";

const AppText = () => (
  <Tooltip title="iOS and Android versions count as separate apps. You can delete unused apps to reclaim quota.">
    <span className="cursor-help border-b border-dashed border-[#d6d3cd] text-[#b45309] transition-colors hover:text-[#78350f]">
      Apps
    </span>
  </Tooltip>
);

const PackageText = () => (
  <Tooltip title="A Native Package refers to a complete apk or ipa base app install file. You can delete unused packages to free up quota.">
    <span className="cursor-help border-b border-dashed border-[#d6d3cd] text-[#b45309] transition-colors hover:text-[#78350f]">
      Native Packages
    </span>
  </Tooltip>
);

const HotUpdateText = () => (
  <Tooltip
    title={`A Hot Update Package refers to the ppk file generated by the "cresc bundle" command (which contains jsbundle, images, and other business logic files). Note: This is NOT the file that users actually download; users download a much smaller incremental patch generated on the server. You can delete unused packages to reclaim quota.`}
  >
    <span className="cursor-help border-b border-dashed border-[#d6d3cd] text-[#b45309] transition-colors hover:text-[#78350f]">
      Hot Update Packages
    </span>
  </Tooltip>
);

const DailyQueriesText = () => (
  <Tooltip
    title="Daily queries counts how many times client devices ask the server whether an update is available, regardless of whether a new version exists."
  >
    <span className="cursor-help border-b border-dashed border-[#d6d3cd] text-[#b45309] transition-colors hover:text-[#78350f]">
      Daily queries
    </span>
  </Tooltip>
);

const MetricRow = ({
  label,
  value,
  valueClassName = "",
}: {
  label: ReactNode;
  value: ReactNode;
  valueClassName?: string;
}) => (
  <div className="grid grid-cols-[minmax(0,1fr)_minmax(11rem,auto)] items-center gap-4 rounded-xl border border-[#eceae5] bg-[#fafaf9] px-4 py-3 transition-all duration-300 group-hover:border-[#dcd9d3] group-hover:bg-white">
    <span className="text-[0.95rem] leading-6 text-[#57534e]">{label}</span>
    <div
      className={`min-w-0 text-right text-[0.95rem] font-semibold leading-6 text-[#1c1917] ${valueClassName}`}
    >
      {value}
    </div>
  </div>
);

type TierKey = keyof typeof quotas;
type TierQuota = (typeof quotas)[TierKey];

interface Tone {
  accent: string;
  accentSoft: string;
  border: string;
  glow: string;
}

interface TierMeta {
  summary: string;
  tone: Tone;
  badge?: string;
}

const neutralTone: Tone = {
  accent: "#b45309",
  accentSoft: "rgba(215, 181, 124, 0.18)",
  border: "#e7e5e1",
  glow: "none",
};

const highlightTone: Tone = {
  accent: "#b45309",
  accentSoft: "rgba(215, 181, 124, 0.3)",
  border: "rgba(180, 83, 9, 0.4)",
  glow: "radial-gradient(circle at top right, rgba(215, 181, 124, 0.16), transparent 58%)",
};

const tierMeta: Record<TierKey, TierMeta> = {
  free: {
    summary: "A quiet starting point for personal apps and small release loops.",
    tone: neutralTone,
  },
  standard: {
    summary: "For growing apps shipping on a steady monthly rhythm.",
    tone: neutralTone,
  },
  premium: {
    summary: "The main tier for production apps with regular release traffic.",
    badge: "Popular",
    tone: highlightTone,
  },
  pro: {
    summary: "For larger teams that need room for heavier binaries and scale.",
    tone: neutralTone,
  },
  max: {
    summary: "For high-volume apps that query often and carry wider fleets.",
    tone: neutralTone,
  },
  ultra: {
    summary: "For very large distribution footprints and sustained daily traffic.",
    tone: neutralTone,
  },
};

const compactFormatter = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 0,
});

function formatSize(size: string) {
  const amount = Number.parseInt(size, 10);

  if (!Number.isFinite(amount)) {
    return size.toUpperCase();
  }

  if (amount >= 1000) {
    const gigabytes = amount / 1000;
    return Number.isInteger(gigabytes)
      ? `${gigabytes} GB`
      : `${gigabytes.toFixed(1)} GB`;
  }

  return `${amount} MB`;
}

function formatQueries(value: number) {
  return `${compactFormatter.format(value)} / day`;
}

function formatQuota(count: number, noun: string, size: string) {
  return `${count} ${noun} · ${formatSize(size)} ea`;
}

function QueryValue({
  value,
}: {
  value: number;
}) {
  return (
    <div className="min-w-[8.6rem] text-right text-[1.45rem] font-semibold leading-none tracking-tight text-[#b45309] sm:text-[1.55rem]">
      <span className="block">
        {formatQueries(value)}
      </span>
    </div>
  );
}

function formatMetricValue(
  tierKey: TierKey,
  kind: "app" | "package" | "bundle",
  quota: TierQuota,
) {
  if ((tierKey === "max" || tierKey === "ultra") && kind !== "app") {
    return "Same limits as Pro";
  }

  if ((tierKey === "max" || tierKey === "ultra") && kind === "app") {
    return "Same limits as Pro";
  }

  if (kind === "app") {
    return `${quota.app} apps`;
  }

  if (kind === "package") {
    return `${quota.package} base pkgs`;
  }

  return formatQuota(quota.bundle, "updates", quota.bundleSize);
}

function cardStyle(tone: Tone): CSSProperties {
  return {
    borderColor: tone.border,
    backgroundImage: tone.glow,
  };
}

function glowStyle(tone: Tone): CSSProperties {
  return {
    background: tone.accentSoft,
  };
}

function ctaStyle(isFree: boolean): CSSProperties {
  return isFree
    ? {
        borderColor: "#d6d3cd",
        backgroundColor: "#ffffff",
        color: "#1c1917",
      }
    : {
        borderColor: "#1c1917",
        backgroundColor: "#1c1917",
        color: "#ffffff",
      };
}

function ctaHoverStyle(isFree: boolean): CSSProperties {
  return isFree
    ? {
        backgroundColor: "#f6f5f2",
        borderColor: "#b8b3ab",
      }
    : {
        backgroundColor: "#372f2b",
        borderColor: "#372f2b",
      };
}

const tiers = (Object.entries(quotas) as [TierKey, TierQuota][])
  .map(([key, quota]) => ({
    key,
    quota,
    meta: tierMeta[key],
  }))
  .sort((left, right) => left.quota.monthlyPrice - right.quota.monthlyPrice);

const freeTier = tiers.find((tier) => tier.key === "free");
const standardTier = tiers.find((tier) => tier.key === "standard");
const premiumTier = tiers.find((tier) => tier.key === "premium");
const advancedTiers = tiers.filter(
  (tier) =>
    tier.key === "pro" || tier.key === "max" || tier.key === "ultra",
);
const upgradePathTiers = tiers.filter(
  (tier) =>
    tier.key === "standard" ||
    tier.key === "premium" ||
    tier.key === "pro" ||
    tier.key === "max" ||
    tier.key === "ultra",
);

const expoPricingRows = [
  {
    title: "Free",
    price: "$0/mo",
    included: "1K update MAUs",
  },
  {
    title: "Starter",
    price: "$19/mo + usage",
    included: "3K update MAUs + 100 GiB",
  },
  {
    title: "Production",
    price: "$199/mo + usage",
    included: "50K update MAUs + 1 TiB",
  },
];

const comparisonRows = [
  {
    scenario: "First paid tier",
    expo: "Starter is $19/mo, then usage-based billing after 3K update MAUs and 100 GiB.",
    cresc: "Standard is $19/mo with 10K update checks per day, CDN delivery included, and no automatic overage bill.",
  },
  {
    scenario: "Production traffic",
    expo: "Production is $199/mo, then usage-based billing after 50K update MAUs and 1 TiB.",
    cresc: "Pro is $99/mo with 1M update checks per day. Upgrade when real traffic needs more headroom.",
  },
  {
    scenario: "High volume",
    expo: "Enterprise pricing is custom, so there is no public monthly number to compare.",
    cresc: "Max and Ultra are fixed public tiers at $399/mo and $1,699/mo, so capacity planning stays explicit.",
  },
];

function PricingCard({
  tierKey,
  quota,
  meta,
}: {
  tierKey: TierKey;
  quota: TierQuota;
  meta: TierMeta;
}) {
  const isFree = quota.monthlyPrice === 0;

  return (
    <section
      className="group relative flex h-full flex-col overflow-hidden rounded-2xl border bg-white p-5 shadow-[0_1px_2px_rgba(28,25,23,0.04)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_20px_44px_-16px_rgba(28,25,23,0.16)] sm:p-6"
      style={cardStyle(meta.tone)}
    >
      <div
        className="pointer-events-none absolute -right-10 -top-10 h-32 w-32 rounded-full blur-3xl transition-transform duration-700 group-hover:scale-125 group-hover:-translate-y-2"
        style={glowStyle(meta.tone)}
      />

      <div className="relative">
        <div className="flex items-center gap-3">
          <h2 className="cresc-display text-2xl text-[#1c1917]">
            {quota.title}
          </h2>
          {meta.badge && (
            <span className="rounded-full border border-[#f0d9bd] bg-[#fdf6ec] px-3 py-1 text-[0.68rem] font-semibold uppercase tracking-[0.14em] text-[#b45309]">
              {meta.badge}
            </span>
          )}
        </div>
        <p className="mt-2.5 max-w-[22rem] text-[0.95rem] leading-6 text-[#57534e]">
          {meta.summary}
        </p>
      </div>

      <div className="relative mt-5 border-t border-[#eceae5] pt-5">
        <div className="flex items-end gap-2 text-[#1c1917]">
          <span className="cresc-display text-[2.6rem] leading-none tracking-tight">
            ${quota.monthlyPrice}
          </span>
          <span className="pb-1 text-sm text-[#78716c]">USD / month</span>
        </div>
      </div>

      <div className="relative mt-5 grid gap-2.5">
        <MetricRow
          label={<DailyQueriesText />}
          value={<QueryValue value={quota.pv} />}
          valueClassName="flex justify-end"
        />
        <MetricRow
          label={<AppText />}
          value={formatMetricValue(tierKey, "app", quota)}
        />
        <MetricRow
          label={<PackageText />}
          value={formatMetricValue(tierKey, "package", quota)}
        />
        <MetricRow
          label={<HotUpdateText />}
          value={formatMetricValue(tierKey, "bundle", quota)}
        />
      </div>

      <a
        href={isFree ? "/docs/getting-started" : "https://admin.cresc.dev"}
        {...(isFree ? {} : { target: "_blank", rel: "noopener noreferrer" })}
        className="group relative mt-6 inline-flex items-center justify-center gap-2 rounded-xl border px-6 py-3.5 text-base font-semibold transition-all duration-200 hover:gap-3"
        style={ctaStyle(isFree)}
        onMouseEnter={(event) => {
          Object.assign(
            (event.currentTarget as HTMLAnchorElement).style,
            ctaHoverStyle(isFree),
          );
        }}
        onMouseLeave={(event) => {
          Object.assign(
            (event.currentTarget as HTMLAnchorElement).style,
            ctaStyle(isFree),
          );
        }}
      >
        <span>{isFree ? "Start free" : "Subscribe"}</span>
        <span className="transition-transform duration-300 group-hover:translate-x-1">
          →
        </span>
      </a>

      <p
        className="relative mt-4 text-xs font-medium uppercase tracking-[0.14em] text-[#a8a29e]"
      >
        CDN delivery included
      </p>
    </section>
  );
}

function CompactFreeRow({ quota }: { quota: TierQuota }) {
  return (
    <section className="rounded-2xl border border-[#e7e5e1] bg-white px-4 py-3.5 text-[#57534e] shadow-[0_1px_2px_rgba(28,25,23,0.04)] sm:px-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex min-w-0 flex-wrap items-center gap-x-3.5 gap-y-1.5 text-[0.92rem] text-[#57534e]">
          <span className="cresc-display text-xl leading-none text-[#1c1917]">
            {quota.title}
          </span>
          <span className="text-[#78716c]">
            USD ${quota.monthlyPrice}/mo
          </span>
          <span className="text-[1.2rem] font-semibold leading-none text-[#b45309]">
            {compactFormatter.format(quota.pv)}/day
          </span>
          <span>{quota.app} apps</span>
          <span>{quota.package} base pkgs</span>
          <span>{quota.bundle} updates · {formatSize(quota.bundleSize)}</span>
          <span className="text-xs font-medium uppercase tracking-[0.12em] text-[#a8a29e]">
            CDN delivery included
          </span>
        </div>
        <a
          href="/docs/getting-started"
          className="inline-flex shrink-0 items-center rounded-xl border border-[#d6d3cd] bg-white px-5 py-2.5 text-sm font-semibold text-[#1c1917] transition-all duration-200 hover:border-[#b45309] hover:text-[#b45309] lg:ml-4"
        >
          Start free
        </a>
      </div>
    </section>
  );
}

function Pricing() {
  const [showAdvanced, setShowAdvanced] = useState(false);
  const advancedRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const node = advancedRef.current;

    if (!node) {
      return;
    }

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry?.isIntersecting) {
          setShowAdvanced(true);
          observer.disconnect();
        }
      },
      {
        threshold: 0.3,
        rootMargin: "0px 0px -10% 0px",
      },
    );

    observer.observe(node);

    return () => observer.disconnect();
  }, []);

  return (
    <div className="relative overflow-hidden bg-[#fdfdfc] px-4 py-16 sm:px-6 lg:px-8">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[22rem] overflow-hidden">
        <div className="absolute left-[-6%] top-[-18%] h-72 w-72 rounded-full bg-[#d7b57c]/20 blur-3xl" />
        <div className="absolute right-[-3%] top-[10%] h-80 w-80 rounded-full bg-[#b45309]/8 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-6xl">
        <div className="mx-auto max-w-3xl text-center">
          <h1 className="cresc-display text-4xl leading-tight text-[#1c1917] sm:text-5xl">
            Simple monthly tiers, arranged by release volume.
          </h1>
          <p className="mx-auto mt-5 w-auto text-lg leading-8 text-[#57534e]">
            Choose a plan based on your release traffic and the amount
            of app history you need to keep available.
          </p>
          <div className="mx-auto mt-5 flex max-w-3xl flex-wrap items-center justify-center gap-x-4 gap-y-2 text-[0.95rem] text-[#57534e]">
            <span className="hidden h-1 w-1 rounded-full bg-[#d6d3cd] sm:block" />
            <span>CDN delivery included on every plan.</span>
            <span className="hidden h-1 w-1 rounded-full bg-[#d6d3cd] md:block" />
            <span>Unused resources can be removed to reclaim quota.</span>
          </div>
        </div>

        {freeTier && (
          <div className="mx-auto mt-10 max-w-5xl">
            <CompactFreeRow quota={freeTier.quota} />
          </div>
        )}

        <div className="mx-auto mt-5 grid max-w-5xl grid-cols-1 gap-5 lg:grid-cols-2">
          <div className="flex flex-col gap-5">
            {standardTier && (
              <PricingCard
                tierKey={standardTier.key}
                quota={standardTier.quota}
                meta={standardTier.meta}
              />
            )}
          </div>

          <div>
            {premiumTier && (
              <PricingCard
                tierKey={premiumTier.key}
                quota={premiumTier.quota}
                meta={premiumTier.meta}
              />
            )}
          </div>
        </div>

        <section className="mx-auto mt-10 max-w-5xl rounded-2xl border border-[#e7e5e1] bg-[#f6f5f2] px-5 py-6 sm:px-7 sm:py-8">
          <div className="max-w-3xl">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#b45309]">
              Pricing Comparison
            </p>
            <h2 className="cresc-display mt-3 text-2xl leading-tight text-[#1c1917] sm:text-3xl">
              Fixed tiers, no runaway bill.
            </h2>
            <p className="mt-4 text-base leading-7 text-[#57534e]">
              Expo EAS Update and Cresc use different meters. Expo counts
              unique users who download an update in a monthly billing period,
              plus edge bandwidth. Cresc uses fixed monthly tiers based on
              daily update checks, with CDN delivery included. There is no
              hidden usage meter that turns a traffic spike into a surprise
              invoice. Pick the tier that fits real traffic, then upgrade only
              when the app needs more headroom.
            </p>
          </div>

          <div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
            <div className="rounded-2xl border border-[#e7e5e1] bg-white p-5">
              <div className="flex items-center justify-between gap-3">
                <h3 className="cresc-display text-xl text-[#1c1917]">
                  Expo EAS Update
                </h3>
                <span className="text-xs font-medium uppercase tracking-[0.12em] text-[#a8a29e]">
                  Checked 2026-04-17
                </span>
              </div>

              <div className="mt-5 grid gap-3">
                {expoPricingRows.map((row) => (
                  <div
                    key={row.title}
                    className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 rounded-xl border border-[#eceae5] bg-[#fafaf9] px-4 py-3"
                  >
                    <div>
                      <p className="font-semibold text-[#1c1917]">{row.title}</p>
                      <p className="mt-1 text-sm leading-6 text-[#57534e]">
                        {row.included}
                      </p>
                    </div>
                    <p className="text-right text-sm font-semibold leading-6 text-[#b45309]">
                      {row.price}
                    </p>
                  </div>
                ))}
              </div>

              <p className="mt-4 text-sm leading-6 text-[#57534e]">
                Expo counts update MAUs only when a device downloads at least
                one update during the billing period. Users who only check for
                updates are not counted as update MAUs.
              </p>
            </div>

            <div className="rounded-2xl border border-[#e7e5e1] bg-white p-5">
              <div className="flex items-center justify-between gap-3">
                <h3 className="cresc-display text-xl text-[#1c1917]">
                  Same monthly scenarios
                </h3>
                <span className="text-xs font-medium uppercase tracking-[0.12em] text-[#a8a29e]">
                  Same basis
                </span>
              </div>

              <div className="mt-5 grid gap-3">
                {comparisonRows.map((row) => (
                  <div
                    key={row.scenario}
                    className="rounded-xl border border-[#eceae5] bg-[#fafaf9] px-4 py-3"
                  >
                    <p className="font-semibold text-[#1c1917]">
                      {row.scenario}
                    </p>
                    <p className="mt-2 text-sm leading-6 text-[#57534e]">
                      <span className="font-semibold text-[#b45309]">Expo:</span>{" "}
                      {row.expo}
                    </p>
                    <p className="mt-1 text-sm leading-6 text-[#57534e]">
                      <span className="font-semibold text-[#b45309]">Cresc:</span>{" "}
                      {row.cresc}
                    </p>
                  </div>
                ))}
              </div>

              <p className="mt-4 text-sm leading-6 text-[#57534e]">
                The direct difference is not that one "daily query" equals one
                Expo MAU. The difference is billing behavior: Cresc stops at
                the tier you choose, while Expo can add usage charges for
                update MAUs and bandwidth after the plan allowance.
              </p>
            </div>
          </div>

          <div className="mt-6 rounded-2xl border border-[#e7e5e1] bg-white p-5">
            <div className="flex items-center justify-between gap-3">
              <h3 className="cresc-display text-xl text-[#1c1917]">
                Cresc upgrade path
              </h3>
              <span className="text-xs font-medium uppercase tracking-[0.12em] text-[#a8a29e]">
                Fixed tiers
              </span>
            </div>

            <p className="mt-3 text-sm leading-6 text-[#57534e]">
              Start with the tier that covers current release traffic. Upgrading
              changes the allowance, not the app integration or release flow, so
              teams can add capacity when real usage requires it instead of
              buying too much headroom early.
            </p>

            <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">
              {upgradePathTiers.map((tier) => (
                <div
                  key={tier.key}
                  className="rounded-xl border border-[#eceae5] bg-[#fafaf9] px-4 py-3"
                >
                  <p className="font-semibold text-[#1c1917]">
                    {tier.quota.title}
                  </p>
                  <p className="mt-1 text-sm leading-6 text-[#57534e]">
                    {formatQueries(tier.quota.pv)} included
                  </p>
                  <p className="mt-2 text-sm font-semibold leading-6 text-[#b45309]">
                    ${tier.quota.monthlyPrice}/mo
                  </p>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm leading-6 text-[#57534e]">
              Want the detailed breakdown, including Expo's own overage example?
            </p>
            <a
              href="/expo-pricing-vs-cresc"
              className="inline-flex items-center justify-center rounded-xl bg-[#1c1917] px-6 py-3 text-sm font-semibold text-white shadow-sm transition duration-200 hover:bg-[#372f2b]"
            >
              Read pricing comparison
            </a>
          </div>
        </section>

        <div
          ref={advancedRef}
          className="relative mx-auto mt-10 max-w-6xl"
        >
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#b45309]">
              Higher Volume
            </p>
            <h2 className="cresc-display mt-3 text-2xl leading-tight text-[#1c1917] sm:text-4xl">
              Pro and above.
            </h2>
          </div>

          <div
            className={`relative mt-6 overflow-hidden rounded-2xl border border-[#e7e5e1] bg-[#f6f5f2] px-4 py-5 transition-all duration-700 sm:px-5 ${
              showAdvanced ? "max-h-[2600px]" : "max-h-24"
            }`}
          >
            <div
              className={`grid grid-cols-1 gap-5 transition-all duration-700 md:grid-cols-2 xl:grid-cols-3 ${
                showAdvanced
                  ? "translate-y-0 scale-100 opacity-100"
                  : "translate-y-10 scale-[0.985] opacity-40"
              }`}
            >
              {advancedTiers.map((tier) => (
                <PricingCard
                  key={tier.key}
                  tierKey={tier.key}
                  quota={tier.quota}
                  meta={tier.meta}
                />
              ))}
            </div>

            {!showAdvanced && (
              <div className="pointer-events-none absolute inset-x-0 bottom-0 h-20 bg-[linear-gradient(180deg,rgba(246,245,242,0)_0%,rgba(246,245,242,0.96)_100%)]" />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Pricing;
