import { Tooltip } from "antd";
import { CheckCircleFilled } from "@ant-design/icons";
import type { ReactNode } from "react";

const AppText = () => (
  <Tooltip title="iOS and Android versions count as separate apps. You can delete unused apps to reclaim your quota.">
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Apps
    </span>
  </Tooltip>
);

const PackageText = () => (
  <Tooltip title="A Native Package refers to a complete apk or ipa base app install file. You can delete unused packages to free up quota.">
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Native Packages
    </span>
  </Tooltip>
);

const HotUpdateText = () => (
  <Tooltip
    title={`A Hot Update Package refers to the ppk file generated by the "cresc bundle" command (which contains jsbundle, images, and other business logic files). Note: This is NOT the file that users actually download; users download a much smaller incremental patch generated on the server. You can delete unused packages to reclaim quota.`}
  >
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Hot Update Packages
    </span>
  </Tooltip>
);

const CheckLimitText = ({ children }: { children: ReactNode }) => (
  <div className="mt-6 rounded-[20px] border border-[#e3d5c0] bg-[#f7efe2] px-4 py-4">
    <p className="text-xs uppercase tracking-[0.28em] text-[#8b5a3c]">
      Across all apps combined
    </p>
    <div className="mt-2 flex items-center gap-1 text-sm text-[#5f483c]">
      Up to
      <Tooltip
        title={
          <div>
            Refers to the number of times client devices query the server for
            updates, regardless of whether a new version exists. If your daily
            queries exceed one million, check out our{" "}
            <a
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-white underline"
              href="/docs/faq#大客户方案"
            >
              Enterprise Solutions
            </a>
            .
          </div>
        }
      >
        <span className="cursor-help border-b border-dashed border-[#c8b28f] font-semibold text-[#7a3b2e]">
          {children}
        </span>
      </Tooltip>
      queries daily
    </div>
  </div>
);

const FeatureItem = ({ children }: { children: ReactNode }) => (
  <li className="flex items-start gap-3 text-[#5f483c]">
    <CheckCircleFilled className="mt-1 text-[#8b5a3c]" />
    <span className="leading-7">{children}</span>
  </li>
);

function DurationNote({
  kind,
}: {
  kind: "eighth" | "quarter" | "half" | "whole";
}) {
  if (kind === "whole") {
    return (
      <svg viewBox="0 0 48 48" className="h-8 w-8" fill="none">
        <ellipse
          cx="24"
          cy="26"
          rx="11"
          ry="7.6"
          transform="rotate(-18 24 26)"
          stroke="currentColor"
          strokeWidth="3.1"
        />
      </svg>
    );
  }

  return (
    <svg viewBox="0 0 48 48" className="h-8 w-8" fill="none">
      <ellipse
        cx="19.5"
        cy="31"
        rx="9.2"
        ry="6.6"
        transform="rotate(-18 19.5 31)"
        fill={kind === "quarter" || kind === "eighth" ? "currentColor" : "#f5ecdf"}
        stroke="currentColor"
        strokeWidth="3"
      />
      <path
        d="M27 28V10"
        stroke="currentColor"
        strokeWidth="3.2"
        strokeLinecap="round"
      />
      {kind === "eighth" && (
        <path
          d="M27 10C33 12.5 36.5 17.2 35.5 21.5C33.2 18.9 30 17.4 27 17.2"
          stroke="currentColor"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      )}
    </svg>
  );
}

interface Plan {
  name: string;
  summary: string;
  price: string;
  monthly?: string;
  queryLimit: string;
  icon: ReactNode;
  ctaLabel: string;
  ctaHref: string;
  external?: boolean;
  featured?: boolean;
  emphasis?: "light" | "solid" | "dark";
  features: ReactNode[];
}

const plans: Plan[] = [
  {
    name: "Free",
    summary: "Suitable for small apps or personal projects with light OTA needs.",
    price: "0",
    queryLimit: "1 Thousand",
    icon: <DurationNote kind="eighth" />,
    ctaLabel: "Get Started",
    ctaHref: "/docs/getting-started",
    emphasis: "light",
    features: [
      <>
        Up to 3 <AppText />
      </>,
      <>
        30 <PackageText /> / App (Max 30M ea)
      </>,
      <>
        30 <HotUpdateText /> / App (Max 3M ea)
      </>,
      <strong className="text-[#6e3428]">Unlimited CDN Bandwidth</strong>,
    ],
  },
  {
    name: "Standard",
    summary: "For general apps with moderate iteration and update frequency.",
    price: "800",
    monthly: "¥100 / month",
    queryLimit: "10 Thousand",
    icon: <DurationNote kind="quarter" />,
    ctaLabel: "Upgrade Now",
    ctaHref: "https://admin.cresc.dev",
    external: true,
    emphasis: "solid",
    features: [
      <>
        Up to 5 <AppText />
      </>,
      <>
        50 <PackageText /> / App (Max 150M ea)
      </>,
      <>
        50 <HotUpdateText /> / App (Max 15M ea)
      </>,
      <strong className="text-[#6e3428]">Unlimited CDN Bandwidth</strong>,
      "Dedicated Technical Support",
    ],
  },
  {
    name: "Premium",
    summary: "For medium-large commercial apps needing fast, reliable live patches.",
    price: "2400",
    monthly: "¥300 / month",
    queryLimit: "100 Thousand",
    icon: <DurationNote kind="half" />,
    ctaLabel: "Buy Now",
    ctaHref: "https://admin.cresc.dev",
    external: true,
    featured: true,
    emphasis: "solid",
    features: [
      <>
        Up to 10 <AppText />
      </>,
      <>
        60 <PackageText /> / App (Max 500M ea)
      </>,
      <>
        60 <HotUpdateText /> / App (Max 50M ea)
      </>,
      <strong className="text-[#6e3428]">Unlimited CDN Bandwidth</strong>,
      <>
        <strong className="text-[#6e3428]">Priority</strong> Technical Support
      </>,
    ],
  },
  {
    name: "Professional",
    summary: "For enterprise multi-business-line applications with extreme limits.",
    price: "7200",
    monthly: "¥900 / month",
    queryLimit: "1 Million",
    icon: <DurationNote kind="whole" />,
    ctaLabel: "Contact Us",
    ctaHref: "https://admin.cresc.dev",
    external: true,
    emphasis: "dark",
    features: [
      <>
        Up to 50 <AppText />
      </>,
      <>
        100 <PackageText /> / App (Max 2000M ea)
      </>,
      <>
        100 <HotUpdateText /> / App (Max 200M ea)
      </>,
      <strong className="text-[#6e3428]">Unlimited CDN Bandwidth</strong>,
      <>
        <strong className="text-[#6e3428]">Highest Tier</strong> Enterprise Support
      </>,
    ],
  },
];

function Pricing() {
  return (
    <div className="relative overflow-hidden bg-[linear-gradient(180deg,#fbf5ea_0%,#f1e6d6_100%)] px-4 py-24 sm:px-6 lg:px-8">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[28rem] overflow-hidden">
        <div className="absolute -left-[8%] top-[-12%] h-72 w-72 rounded-full bg-[#d9c0a2]/45 blur-3xl" />
        <div className="absolute right-[-4%] top-[8%] h-80 w-80 rounded-full bg-[#c99079]/18 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-7xl">
        <div className="mx-auto max-w-3xl text-center">
          <p className="text-sm uppercase tracking-[0.42em] text-[#8b5a3c]">
            Pricing
          </p>
          <h1 className="cresc-display mt-5 text-5xl text-[#2d1d15] sm:text-6xl">
            Plans shaped for a steadier release pace.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#5f483c]">
            Every new account begins with a{" "}
            <Tooltip title="Send your username and company (or personal) name to hi@charmlot.com to request an extended trial evaluation period.">
              <span className="cursor-help border-b border-dashed border-[#c8b28f] font-semibold text-[#7a3b2e]">
                7-day
              </span>
            </Tooltip>{" "}
            trial of the Professional plan. After the trial ends, the account
            returns to Free. For monthly billing or enterprise arrangements,
            please contact QQ Customer Service 34731408.
          </p>
        </div>

        <div className="mx-auto mt-12 max-w-5xl rounded-[30px] border border-[#ddcdb3] bg-[#fffaf4]/90 px-8 py-7 text-center shadow-[0_18px_40px_rgba(113,88,67,0.08)]">
          <p className="text-sm uppercase tracking-[0.32em] text-[#8b5a3c]">
            Billing note
          </p>
          <p className="mt-3 text-lg leading-8 text-[#5f483c]">
            All tiers include CDN bandwidth. Storage limits apply per app, and
            unused apps or packages can be removed at any time to free quota.
          </p>
        </div>

        <div className="mt-14 grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-4">
          {plans.map((plan) => {
            const ctaClassName =
              plan.emphasis === "light"
                ? "border border-[#d6c0a0] bg-[#fffaf2] text-[#3f2b21] hover:border-[#7a3b2e] hover:text-[#7a3b2e]"
                : plan.emphasis === "dark"
                  ? "border border-[#4f2a20] bg-[#4f2a20] text-[#fffaf4] hover:bg-[#3f2018]"
                  : "border border-[#7a3b2e] bg-[#7a3b2e] text-[#fffaf4] hover:bg-[#6a3025]";

            return (
              <div
                key={plan.name}
                className={`relative flex h-full flex-col rounded-[32px] border p-8 shadow-[0_18px_40px_rgba(113,88,67,0.08)] transition-transform duration-300 hover:-translate-y-1 ${
                  plan.featured
                    ? "border-[#b78057] bg-[#fff9f1]"
                    : "border-[#ddcdb3] bg-[#fffaf4]/95"
                }`}
              >
                {plan.featured && (
                  <div className="absolute left-8 top-0 -translate-y-1/2 rounded-full border border-[#cfaa82] bg-[#f7ecdd] px-4 py-1 text-xs uppercase tracking-[0.3em] text-[#7a3b2e]">
                    Recommended
                  </div>
                )}

                <div className="flex items-start justify-between gap-4">
                  <div>
                    <h2 className="cresc-display text-4xl text-[#2d1d15]">
                      {plan.name}
                    </h2>
                    <p className="mt-3 min-h-16 text-sm leading-7 text-[#6a5245]">
                      {plan.summary}
                    </p>
                  </div>
                  <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-[#d6c0a0] bg-[#f5ecdf] text-[#7a3b2e]">
                    {plan.icon}
                  </div>
                </div>

                <div className="mt-8 border-t border-[#eadbc7] pt-7">
                  <div className="flex items-baseline text-[#2d1d15]">
                    <span className="text-3xl font-semibold">¥</span>
                    <span className="ml-1 text-5xl font-semibold tracking-tight">
                      {plan.price}
                    </span>
                    <span className="ml-2 text-base text-[#6a5245]">/ year</span>
                  </div>
                  {plan.monthly && (
                    <p className="mt-3 text-sm text-[#8b7568]">{plan.monthly}</p>
                  )}
                </div>

                <ul className="mt-8 flex-1 space-y-4">
                  {plan.features.map((feature, index) => (
                    <FeatureItem key={`${plan.name}-${index}`}>{feature}</FeatureItem>
                  ))}
                </ul>

                <CheckLimitText>{plan.queryLimit}</CheckLimitText>

                <a
                  href={plan.ctaHref}
                  {...(plan.external
                    ? { target: "_blank", rel: "noopener noreferrer" }
                    : {})}
                  className={`mt-8 inline-flex items-center justify-center rounded-full px-6 py-4 text-base font-semibold transition duration-300 hover:-translate-y-1 ${ctaClassName}`}
                >
                  {plan.ctaLabel}
                </a>
              </div>
            );
          })}
        </div>

        <div className="mx-auto mt-16 max-w-4xl rounded-[28px] border border-[#ddcdb3] bg-[#f7efe2] px-8 py-7 text-center shadow-[0_18px_40px_rgba(113,88,67,0.06)]">
          <p className="text-base leading-8 text-[#5f483c]">
            Native packages are complete apk or ipa base builds. Hot update
            packages are the ppk bundles generated by the CLI rather than the
            files end users download directly.
          </p>
          <p className="mt-4 text-base leading-8 text-[#5f483c]">
            Questions about billing or payments can be answered in our{" "}
            <a
              className="font-semibold text-[#7a3b2e] underline decoration-[#c8b28f] underline-offset-4"
              href="/docs/faq#%E4%BB%98%E8%B4%B9%E9%97%AE%E9%A2%98"
            >
              FAQ
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
}

export default Pricing;
