import { Tooltip } from "antd";
import type { CSSProperties, ReactNode } from "react";
import { useEffect, useRef, useState } from "react";

import { quotas } from "./quota";

const AppText = () => (
  <Tooltip title="iOS and Android versions count as separate apps. You can delete unused apps to reclaim quota.">
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Apps
    </span>
  </Tooltip>
);

const PackageText = () => (
  <Tooltip title="A Native Package refers to a complete apk or ipa base app install file. You can delete unused packages to free up quota.">
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Native Packages
    </span>
  </Tooltip>
);

const HotUpdateText = () => (
  <Tooltip
    title={`A Hot Update Package refers to the ppk file generated by the "cresc bundle" command (which contains jsbundle, images, and other business logic files). Note: This is NOT the file that users actually download; users download a much smaller incremental patch generated on the server. You can delete unused packages to reclaim quota.`}
  >
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Hot Update Packages
    </span>
  </Tooltip>
);

const DailyQueriesText = () => (
  <Tooltip
    title="Daily queries counts how many times client devices ask the server whether an update is available, regardless of whether a new version exists."
  >
    <span className="cursor-help border-b border-dashed border-[#c8b28f] text-[#7a3b2e] transition-colors hover:text-[#5f2a20]">
      Daily queries
    </span>
  </Tooltip>
);

const MetricRow = ({
  label,
  value,
  valueClassName = "",
}: {
  label: ReactNode;
  value: ReactNode;
  valueClassName?: string;
}) => (
  <div className="grid grid-cols-[minmax(0,1fr)_minmax(11rem,auto)] items-center gap-4 rounded-[18px] border border-[#eadbc7] bg-[#fffdf9]/92 px-4 py-3 transition-all duration-300 group-hover:border-[#d3b38c] group-hover:bg-[#fffdf9]">
    <span className="text-base leading-7 text-[#6a5245]">{label}</span>
    <div
      className={`min-w-0 text-right text-base font-semibold leading-7 text-[#2d1d15] ${valueClassName}`}
    >
      {value}
    </div>
  </div>
);

type TierKey = keyof typeof quotas;
type TierQuota = (typeof quotas)[TierKey];

interface Tone {
  accent: string;
  accentSoft: string;
  border: string;
  glow: string;
  cta: string;
  ctaHover: string;
}

interface TierMeta {
  summary: string;
  tone: Tone;
  badge?: string;
}

const tierMeta: Record<TierKey, TierMeta> = {
  free: {
    summary: "A quiet starting point for personal apps and small release loops.",
    tone: {
      accent: "#b07d54",
      accentSoft: "rgba(214, 184, 147, 0.26)",
      border: "#dbc6aa",
      glow: "radial-gradient(circle_at_top_right, rgba(209,171,126,0.30), transparent 58%)",
      cta: "#fff8ef",
      ctaHover: "#f2e1cb",
    },
  },
  standard: {
    summary: "For growing apps shipping on a steady monthly rhythm.",
    tone: {
      accent: "#91503b",
      accentSoft: "rgba(190, 123, 96, 0.24)",
      border: "#d7bea5",
      glow: "radial-gradient(circle_at_top_right, rgba(196,128,98,0.28), transparent 58%)",
      cta: "#7a3b2e",
      ctaHover: "#683024",
    },
  },
  premium: {
    summary: "The main tier for production apps with regular release traffic.",
    badge: "Popular",
    tone: {
      accent: "#8e4330",
      accentSoft: "rgba(205, 145, 102, 0.26)",
      border: "#c98c62",
      glow: "radial-gradient(circle_at_top_right, rgba(214,150,93,0.34), transparent 58%)",
      cta: "#7a3b2e",
      ctaHover: "#5f2a20",
    },
  },
  pro: {
    summary: "For larger teams that need room for heavier binaries and scale.",
    tone: {
      accent: "#5e3427",
      accentSoft: "rgba(111, 78, 61, 0.24)",
      border: "#cbb59b",
      glow: "radial-gradient(circle_at_top_right, rgba(130,100,80,0.26), transparent 58%)",
      cta: "#4f2a20",
      ctaHover: "#3c1f17",
    },
  },
  max: {
    summary: "For high-volume apps that query often and carry wider fleets.",
    tone: {
      accent: "#744935",
      accentSoft: "rgba(149, 114, 87, 0.24)",
      border: "#d4bca3",
      glow: "radial-gradient(circle_at_top_right, rgba(184,138,97,0.28), transparent 58%)",
      cta: "#6d3729",
      ctaHover: "#5d2f22",
    },
  },
  ultra: {
    summary: "For very large distribution footprints and sustained daily traffic.",
    tone: {
      accent: "#5d2f28",
      accentSoft: "rgba(122, 77, 66, 0.24)",
      border: "#ccb39c",
      glow: "radial-gradient(circle_at_top_right, rgba(159,110,90,0.30), transparent 58%)",
      cta: "#4f2a20",
      ctaHover: "#3f2018",
    },
  },
};

const compactFormatter = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 0,
});

function formatSize(size: string) {
  const amount = Number.parseInt(size, 10);

  if (!Number.isFinite(amount)) {
    return size.toUpperCase();
  }

  if (amount >= 1000) {
    const gigabytes = amount / 1000;
    return Number.isInteger(gigabytes)
      ? `${gigabytes} GB`
      : `${gigabytes.toFixed(1)} GB`;
  }

  return `${amount} MB`;
}

function formatQueries(value: number) {
  return `${compactFormatter.format(value)} / day`;
}

function formatQuota(count: number, size: string) {
  return `${count} / app · ${formatSize(size)} ea`;
}

function QueryValue({
  value,
}: {
  value: number;
}) {
  return (
    <div className="min-w-[8.6rem] text-right text-[1.62rem] font-semibold leading-none text-[#7a3b2e] sm:text-[1.75rem]">
      <span className="block">
        {formatQueries(value)}
      </span>
    </div>
  );
}

function formatMetricValue(
  tierKey: TierKey,
  kind: "app" | "package" | "bundle",
  quota: TierQuota,
) {
  if ((tierKey === "max" || tierKey === "ultra") && kind !== "app") {
    return "Same limits as Pro";
  }

  if ((tierKey === "max" || tierKey === "ultra") && kind === "app") {
    return "Same limits as Pro";
  }

  if (kind === "app") {
    return `Up to ${quota.app}`;
  }

  if (kind === "package") {
    return formatQuota(quota.package, quota.packageSize);
  }

  return formatQuota(quota.bundle, quota.bundleSize);
}

function cardStyle(tone: Tone): CSSProperties {
  return {
    borderColor: tone.border,
    backgroundImage: tone.glow,
  };
}

function glowStyle(tone: Tone): CSSProperties {
  return {
    background: tone.accentSoft,
  };
}

function ctaStyle(tone: Tone, isFree: boolean): CSSProperties {
  return isFree
    ? {
        borderColor: tone.border,
        backgroundColor: tone.cta,
        color: "#3f2b21",
      }
    : {
        borderColor: "#7a3b2e",
        backgroundColor: "#7a3b2e",
        color: "#fffaf4",
      };
}

function ctaHoverStyle(tone: Tone, isFree: boolean): CSSProperties {
  return {
    backgroundColor: isFree ? tone.ctaHover : "#5f2a20",
    borderColor: isFree ? tone.accent : "#5f2a20",
  };
}

const tiers = (Object.entries(quotas) as [TierKey, TierQuota][])
  .map(([key, quota]) => ({
    key,
    quota,
    meta: tierMeta[key],
  }))
  .sort((left, right) => left.quota.monthlyPrice - right.quota.monthlyPrice);

const freeTier = tiers.find((tier) => tier.key === "free");
const standardTier = tiers.find((tier) => tier.key === "standard");
const premiumTier = tiers.find((tier) => tier.key === "premium");
const advancedTiers = tiers.filter(
  (tier) =>
    tier.key === "pro" || tier.key === "max" || tier.key === "ultra",
);
const upgradePathTiers = tiers.filter(
  (tier) =>
    tier.key === "standard" ||
    tier.key === "premium" ||
    tier.key === "pro" ||
    tier.key === "max" ||
    tier.key === "ultra",
);

const expoPricingRows = [
  {
    title: "Free",
    price: "$0/mo",
    included: "1K update MAUs",
  },
  {
    title: "Starter",
    price: "$19/mo + usage",
    included: "3K update MAUs + 100 GiB",
  },
  {
    title: "Production",
    price: "$199/mo + usage",
    included: "50K update MAUs + 1 TiB",
  },
];

const comparisonRows = [
  {
    scenario: "First paid tier",
    expo: "Starter is $19/mo, then usage-based billing after 3K update MAUs and 100 GiB.",
    cresc: "Standard is $19/mo with 10K update checks per day, CDN delivery included, and no automatic overage bill.",
  },
  {
    scenario: "Production traffic",
    expo: "Production is $199/mo, then usage-based billing after 50K update MAUs and 1 TiB.",
    cresc: "Pro is $99/mo with 1M update checks per day. Upgrade when real traffic needs more headroom.",
  },
  {
    scenario: "High volume",
    expo: "Enterprise pricing is custom, so there is no public monthly number to compare.",
    cresc: "Max and Ultra are fixed public tiers at $399/mo and $1,699/mo, so capacity planning stays explicit.",
  },
];

function PricingCard({
  tierKey,
  quota,
  meta,
}: {
  tierKey: TierKey;
  quota: TierQuota;
  meta: TierMeta;
}) {
  const isFree = quota.monthlyPrice === 0;

  return (
    <section
      className="group relative flex h-full flex-col overflow-hidden rounded-[30px] border bg-[#fffaf4]/96 p-5 shadow-[0_18px_36px_rgba(113,88,67,0.08)] transition-all duration-500 hover:-translate-y-2 hover:shadow-[0_24px_56px_rgba(113,88,67,0.14)] sm:p-6"
      style={cardStyle(meta.tone)}
    >
      <div
        className="pointer-events-none absolute -right-10 -top-10 h-32 w-32 rounded-full blur-3xl transition-transform duration-700 group-hover:scale-125 group-hover:-translate-y-2"
        style={glowStyle(meta.tone)}
      />
      <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(135deg,rgba(255,255,255,0.18),transparent_42%,rgba(255,255,255,0.12))] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />

      <div className="relative">
        <div className="flex items-center gap-3">
          <h2 className="cresc-display text-[2.5rem] leading-none text-[#2d1d15]">
            {quota.title}
          </h2>
          {meta.badge && (
            <span className="rounded-full border border-[#d8bf9b] bg-[#fbf1e5] px-3 py-1 text-[0.7rem] uppercase tracking-[0.28em] text-[#8b5a3c]">
              {meta.badge}
            </span>
          )}
        </div>
        <p className="mt-3 max-w-[22rem] text-base leading-7 text-[#6a5245]">
          {meta.summary}
        </p>
      </div>

      <div className="relative mt-6 border-t border-[#eadbc7] pt-5">
        <div className="flex items-end gap-2 text-[#2d1d15]">
          <span className="pb-1 text-base uppercase tracking-[0.22em] text-[#8b5a3c]">
            USD
          </span>
          <span className="text-5xl font-semibold tracking-tight">
            ${quota.monthlyPrice}
          </span>
          <span className="pb-1 text-base text-[#6a5245]">/ month</span>
        </div>
      </div>

      <div className="relative mt-6 grid gap-3">
        <MetricRow
          label={<DailyQueriesText />}
          value={<QueryValue value={quota.pv} />}
          valueClassName="flex justify-end"
        />
        <MetricRow
          label={<AppText />}
          value={formatMetricValue(tierKey, "app", quota)}
        />
        <MetricRow
          label={<PackageText />}
          value={formatMetricValue(tierKey, "package", quota)}
        />
        <MetricRow
          label={<HotUpdateText />}
          value={formatMetricValue(tierKey, "bundle", quota)}
        />
      </div>

      <a
        href={isFree ? "/docs/getting-started" : "https://admin.cresc.dev"}
        {...(isFree ? {} : { target: "_blank", rel: "noopener noreferrer" })}
        className="group relative mt-6 inline-flex items-center justify-center gap-2 rounded-full border px-6 py-4 text-base font-semibold transition-all duration-300 hover:-translate-y-1 hover:gap-3"
        style={ctaStyle(meta.tone, isFree)}
        onMouseEnter={(event) => {
          Object.assign(
            (event.currentTarget as HTMLAnchorElement).style,
            ctaHoverStyle(meta.tone, isFree),
          );
        }}
        onMouseLeave={(event) => {
          Object.assign(
            (event.currentTarget as HTMLAnchorElement).style,
            ctaStyle(meta.tone, isFree),
          );
        }}
      >
        <span>{isFree ? "Start free" : "Subscribe"}</span>
        <span className="transition-transform duration-300 group-hover:translate-x-1">
          +
        </span>
      </a>

      <p
        className="relative mt-4 text-sm uppercase tracking-[0.22em] text-[#8b7568]"
      >
        CDN delivery included
      </p>
    </section>
  );
}

function CompactFreeRow({ quota }: { quota: TierQuota }) {
  return (
    <section className="rounded-[24px] border border-[#e7dbcd] bg-[#f8f1e7]/82 px-4 py-3.5 text-[#86776d] shadow-[0_10px_20px_rgba(113,88,67,0.04)] sm:px-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex min-w-0 flex-wrap items-center gap-x-3.5 gap-y-1.5 text-[0.94rem] text-[#7a685c]">
          <span className="cresc-display text-[1.82rem] leading-none text-[#6e5f55]">
            {quota.title}
          </span>
          <span className="uppercase tracking-[0.14em] text-[#948478]">
            USD ${quota.monthlyPrice}/mo
          </span>
          <span className="text-[1.45rem] font-semibold leading-none text-[#7a3b2e]">
            {compactFormatter.format(quota.pv)}/day
          </span>
          <span>{quota.app} apps</span>
          <span>{quota.package} base pkgs · {formatSize(quota.packageSize)}</span>
          <span>{quota.bundle} updates · {formatSize(quota.bundleSize)}</span>
          <span className="uppercase tracking-[0.18em] text-[#9c8a7d]">
            CDN delivery included
          </span>
        </div>
        <a
          href="/docs/getting-started"
          className="inline-flex shrink-0 items-center rounded-full border border-[#d8c9b8] bg-[#fbf6ef] px-5 py-2.5 text-base font-semibold text-[#75665c] transition-all duration-300 hover:-translate-y-0.5 hover:border-[#baa287] hover:text-[#5f473a] lg:ml-4"
        >
          Start free
        </a>
      </div>
    </section>
  );
}

function Pricing() {
  const [showAdvanced, setShowAdvanced] = useState(false);
  const advancedRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const node = advancedRef.current;

    if (!node) {
      return;
    }

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry?.isIntersecting) {
          setShowAdvanced(true);
          observer.disconnect();
        }
      },
      {
        threshold: 0.3,
        rootMargin: "0px 0px -10% 0px",
      },
    );

    observer.observe(node);

    return () => observer.disconnect();
  }, []);

  return (
    <div className="relative overflow-hidden bg-[linear-gradient(180deg,#fbf5ea_0%,#f0e4d1_100%)] px-4 py-16 sm:px-6 lg:px-8">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[22rem] overflow-hidden">
        <div className="absolute left-[-6%] top-[-18%] h-72 w-72 rounded-full bg-[#d9c0a2]/35 blur-3xl" />
        <div className="absolute right-[-3%] top-[10%] h-80 w-80 rounded-full bg-[#c99079]/14 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-6xl">
        <div className="mx-auto max-w-3xl text-center">
          <h1 className="cresc-display text-4xl text-[#2d1d15] sm:text-5xl">
            Simple monthly tiers, arranged by release volume.
          </h1>
          <p className="mx-auto mt-5 w-auto text-lg leading-8 text-[#5f483c]">
            Choose a plan based on your release traffic and the amount
            of app history you need to keep available.
          </p>
          <div className="mx-auto mt-5 flex max-w-3xl flex-wrap items-center justify-center gap-x-4 gap-y-2 text-base text-[#6a5245]">
            <span className="hidden h-1 w-1 rounded-full bg-[#c8b28f] sm:block" />
            <span>CDN delivery included on every plan.</span>
            <span className="hidden h-1 w-1 rounded-full bg-[#c8b28f] md:block" />
            <span>Unused resources can be removed to reclaim quota.</span>
          </div>
        </div>

        {freeTier && (
          <div className="mx-auto mt-10 max-w-5xl">
            <CompactFreeRow quota={freeTier.quota} />
          </div>
        )}

        <div className="mx-auto mt-5 grid max-w-5xl grid-cols-1 gap-5 lg:grid-cols-2">
          <div className="flex flex-col gap-5">
            {standardTier && (
              <PricingCard
                tierKey={standardTier.key}
                quota={standardTier.quota}
                meta={standardTier.meta}
              />
            )}
          </div>

          <div>
            {premiumTier && (
              <PricingCard
                tierKey={premiumTier.key}
                quota={premiumTier.quota}
                meta={premiumTier.meta}
              />
            )}
          </div>
        </div>

        <section className="mx-auto mt-10 max-w-5xl rounded-[34px] border border-[#dcc9ae] bg-[#f8efe2]/80 px-5 py-6 shadow-[0_16px_36px_rgba(113,88,67,0.06)] sm:px-7 sm:py-8">
          <div className="max-w-3xl">
            <p className="text-xs uppercase tracking-[0.34em] text-[#8b5a3c]">
              Pricing Comparison
            </p>
            <h2 className="cresc-display mt-4 text-3xl text-[#2d1d15] sm:text-[2.4rem]">
              Fixed tiers, no runaway bill.
            </h2>
            <p className="mt-4 text-base leading-8 text-[#5f483c]">
              Expo EAS Update and Cresc use different meters. Expo counts
              unique users who download an update in a monthly billing period,
              plus edge bandwidth. Cresc uses fixed monthly tiers based on
              daily update checks, with CDN delivery included. There is no
              hidden usage meter that turns a traffic spike into a surprise
              invoice. Pick the tier that fits real traffic, then upgrade only
              when the app needs more headroom.
            </p>
          </div>

          <div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
            <div className="rounded-[28px] border border-[#e4d3bd] bg-[#fffaf4] p-5">
              <div className="flex items-center justify-between gap-3">
                <h3 className="cresc-display text-[2rem] text-[#2d1d15]">
                  Expo EAS Update
                </h3>
                <span className="text-xs uppercase tracking-[0.2em] text-[#8b5a3c]">
                  Checked 2026-04-17
                </span>
              </div>

              <div className="mt-5 grid gap-3">
                {expoPricingRows.map((row) => (
                  <div
                    key={row.title}
                    className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 rounded-[20px] border border-[#eadbc7] bg-[#fffdf9] px-4 py-3"
                  >
                    <div>
                      <p className="font-semibold text-[#2d1d15]">{row.title}</p>
                      <p className="mt-1 text-sm leading-6 text-[#6a5245]">
                        {row.included}
                      </p>
                    </div>
                    <p className="text-right text-sm font-semibold leading-6 text-[#7a3b2e]">
                      {row.price}
                    </p>
                  </div>
                ))}
              </div>

              <p className="mt-4 text-sm leading-7 text-[#6a5245]">
                Expo counts update MAUs only when a device downloads at least
                one update during the billing period. Users who only check for
                updates are not counted as update MAUs.
              </p>
            </div>

            <div className="rounded-[28px] border border-[#e4d3bd] bg-[#fffaf4] p-5">
              <div className="flex items-center justify-between gap-3">
                <h3 className="cresc-display text-[2rem] text-[#2d1d15]">
                  Same monthly scenarios
                </h3>
                <span className="text-xs uppercase tracking-[0.2em] text-[#8b5a3c]">
                  Same basis
                </span>
              </div>

              <div className="mt-5 grid gap-3">
                {comparisonRows.map((row) => (
                  <div
                    key={row.scenario}
                    className="rounded-[20px] border border-[#eadbc7] bg-[#fffdf9] px-4 py-3"
                  >
                    <p className="font-semibold text-[#2d1d15]">
                      {row.scenario}
                    </p>
                    <p className="mt-2 text-sm leading-6 text-[#6a5245]">
                      <span className="font-semibold text-[#7a3b2e]">Expo:</span>{" "}
                      {row.expo}
                    </p>
                    <p className="mt-1 text-sm leading-6 text-[#6a5245]">
                      <span className="font-semibold text-[#7a3b2e]">Cresc:</span>{" "}
                      {row.cresc}
                    </p>
                  </div>
                ))}
              </div>

              <p className="mt-4 text-sm leading-7 text-[#6a5245]">
                The direct difference is not that one "daily query" equals one
                Expo MAU. The difference is billing behavior: Cresc stops at
                the tier you choose, while Expo can add usage charges for
                update MAUs and bandwidth after the plan allowance.
              </p>
            </div>
          </div>

          <div className="mt-6 rounded-[24px] border border-[#e4d3bd] bg-[#fffaf4] p-5">
            <div className="flex items-center justify-between gap-3">
              <h3 className="cresc-display text-[2rem] text-[#2d1d15]">
                Cresc upgrade path
              </h3>
              <span className="text-xs uppercase tracking-[0.2em] text-[#8b5a3c]">
                Fixed tiers
              </span>
            </div>

            <p className="mt-3 text-sm leading-7 text-[#6a5245]">
              Start with the tier that covers current release traffic. Upgrading
              changes the allowance, not the app integration or release flow, so
              teams can add capacity when real usage requires it instead of
              buying too much headroom early.
            </p>

            <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">
              {upgradePathTiers.map((tier) => (
                <div
                  key={tier.key}
                  className="rounded-[20px] border border-[#eadbc7] bg-[#fffdf9] px-4 py-3"
                >
                  <p className="font-semibold text-[#2d1d15]">
                    {tier.quota.title}
                  </p>
                  <p className="mt-1 text-sm leading-6 text-[#6a5245]">
                    {formatQueries(tier.quota.pv)} included
                  </p>
                  <p className="mt-2 text-sm font-semibold leading-6 text-[#7a3b2e]">
                    ${tier.quota.monthlyPrice}/mo
                  </p>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm leading-7 text-[#6a5245]">
              Want the detailed breakdown, including Expo's own overage example?
            </p>
            <a
              href="/expo-pricing-vs-cresc"
              className="inline-flex items-center justify-center rounded-full border border-[#7a3b2e] bg-[#7a3b2e] px-6 py-3 text-sm font-semibold text-[#fffaf4] transition duration-300 hover:-translate-y-1 hover:bg-[#5f2a20]"
            >
              Read pricing comparison
            </a>
          </div>
        </section>

        <div
          ref={advancedRef}
          className="relative mx-auto mt-10 max-w-6xl"
        >
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-xs uppercase tracking-[0.34em] text-[#8b5a3c]">
              Higher Volume
            </p>
            <h2 className="cresc-display mt-4 text-3xl text-[#2d1d15] sm:text-[2.7rem]">
              Pro and above.
            </h2>
          </div>

          <div
            className={`relative mt-6 overflow-hidden rounded-[34px] border border-[#dcc9ae] bg-[#f8efe2]/72 px-4 py-5 shadow-[0_16px_36px_rgba(113,88,67,0.06)] transition-all duration-700 sm:px-5 ${
              showAdvanced ? "max-h-[2600px]" : "max-h-24"
            }`}
          >
            <div
              className={`grid grid-cols-1 gap-5 transition-all duration-700 md:grid-cols-2 xl:grid-cols-3 ${
                showAdvanced
                  ? "translate-y-0 scale-100 opacity-100"
                  : "translate-y-10 scale-[0.985] opacity-40"
              }`}
            >
              {advancedTiers.map((tier) => (
                <PricingCard
                  key={tier.key}
                  tierKey={tier.key}
                  quota={tier.quota}
                  meta={tier.meta}
                />
              ))}
            </div>

            {!showAdvanced && (
              <div className="pointer-events-none absolute inset-x-0 bottom-0 h-20 bg-[linear-gradient(180deg,rgba(248,239,226,0)_0%,rgba(248,239,226,0.96)_100%)]" />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Pricing;
